const fs = require('fs');
const path = require('path');
const https = require('https');

let envConfig = {};
try {
  const envFile = fs.readFileSync(path.join(__dirname, '.env.local'), 'utf-8');
  envFile.split('\n').forEach(line => {
    if (line && line.includes('=')) {
      const [key, ...value] = line.split('=');
      envConfig[key.trim()] = value.join('=').trim().replace(/^['"]|['"]$/g, '');
    }
  });
} catch(e) {}
const GOOGLE_API_KEY = envConfig.VITE_GOOGLE_TRANSLATE_API_KEY || process.env.VITE_GOOGLE_TRANSLATE_API_KEY;

const languages = [
  'en', 'id', 'es', 'fr', 'de', 'zh', 'ja', 'ko', 'ru', 'ar', 
  'pt', 'it', 'hi', 'bn', 'ur', 'tr', 'vi', 'th', 'nl', 'pl', 
  'sv', 'fi', 'da', 'no', 'cs', 'el', 'he', 'ms', 'tl', 'uk'
];

function translateText(text, targetLang) {
  return new Promise((resolve) => {
    if (targetLang === 'en') return resolve(text);
    
    const postData = JSON.stringify({ q: text, target: targetLang, format: 'text' });
    const options = {
      hostname: 'translation.googleapis.com',
      path: `/language/translate/v2?key=${GOOGLE_API_KEY}`,
      method: 'POST',
      headers: { 'Content-Type': 'application/json', 'Content-Length': Buffer.byteLength(postData) }
    };
    const req = https.request(options, (res) => {
      let data = '';
      res.on('data', chunk => { data += chunk; });
      res.on('end', () => {
        try {
          const parsed = JSON.parse(data);
          resolve(parsed.data.translations[0].translatedText);
        } catch (e) { resolve(text); }
      });
    });
    req.on('error', () => resolve(text));
    req.write(postData);
    req.end();
  });
}

function slugify(text) {
  return text.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)+/g, '');
}

async function run() {
  const file = path.join(__dirname, 'src', 'config', 'localizedRoutes.js');
  let content = fs.readFileSync(file, 'utf8');
  
  // Extract the objects
  const localizedRoutesMatch = content.match(/export const localizedRoutes = (\{[\s\S]*?\n\});/);
  const routeToToolMapMatch = content.match(/export const routeToToolMap = (\{[\s\S]*?\n\});/);
  
  if (!localizedRoutesMatch || !routeToToolMapMatch) {
    console.error("Could not parse file.");
    return;
  }
  
  let localizedRoutes = eval('(' + localizedRoutesMatch[1] + ')');
  let routeToToolMap = eval('(' + routeToToolMapMatch[1] + ')');
  
  for (const lang of languages) {
    if (!localizedRoutes[lang]) localizedRoutes[lang] = {};
    if (!routeToToolMap[lang]) routeToToolMap[lang] = {};
    
    if (!localizedRoutes[lang].scanbarcode) {
      console.log(`Processing scanbarcode route for ${lang}...`);
      let slugBase = 'barcode-scanner-online';
      if (lang !== 'en') {
        const translated = await translateText('barcode scanner online', lang);
        slugBase = slugify(translated);
      }
      const newSlug = `/${slugBase}`;
      
      localizedRoutes[lang].scanbarcode = newSlug;
      routeToToolMap[lang][newSlug] = "scanbarcode";
    }
  }
  
  const newContent = `// Auto-generated by generate-localized-routes-fast.cjs
export const localizedRoutes = ${JSON.stringify(localizedRoutes, null, 2)};

export const routeToToolMap = ${JSON.stringify(routeToToolMap, null, 2)};
`;

  fs.writeFileSync(file, newContent);
  console.log("Done patching localizedRoutes.js!");
}

run();
